## 2D Array - DS

Given a *6 x 6* 2D Array, *arr*:

$$
\begin{equation}
\begin{matrix}

1 & 1 & 1 & 0 & 0 & 0\\
0 & 1 & 0 & 0 & 0 & 0\\
1 & 1 & 1 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0\\

\end{matrix}
\end{equation}
$$

An hourglass in *A* is a subset of values with indices falling in this pattern in *arr*'s graphical representation:

$$
\begin{equation}
\begin{matrix}

a & b & c\\
  & d &  \\
e & f & g\\

\end{matrix}
\end{equation}
$$

There are *16* hourglasses in *arr*. An hourglass sum is the sum of an hourglass' values. Calculate the hourglass sum for every hourglass in *arr* , then print the maximum hourglass sum. The array will always be .

**Example**

arr =

$$
\begin{equation}
\begin{matrix}

-9 & -9 & -9 & 1 &  1 & 1\\
 0 & -9 &  0 & 4 &  3 & 2\\
-9 & -9 & -9 & 1 &  2 & 3\\
 0 &  0 &  8 & 6 &  6 & 0\\
 0 &  0 &  0 & 0 & -2 & 0\\
 0 &  0 &  1 & 2 &  4 & 0\\

\end{matrix}
\end{equation}
$$

The *16* hourglass sums are:

$$
\begin{equation}
\begin{matrix}


-63 & -34 & -9 & 12\\
-10 & 0 &  28 & 23\\
-27 & -11 & -2 & 10\\
9 &  17 &  25 & 18\\

\end{matrix}
\end{equation}
$$

The highest hourglass sum is *26* from the hourglass beginning at row *1*, column *2*:

 $$
\begin{equation}
\begin{matrix}

0 & 4 & 3\\
  & 1 &  \\
8 & 8 & 6\\

\end{matrix}
\end{equation}
$$

Note: If you have already solved the Java domain's Java 2D Array challenge, you may wish to skip this challenge.

**Function Description**

Complete the function hourglassSum in the editor below.

hourglassSum has the following parameter(s):

- int arr[6][6]: an array of integers

**Returns**

- int: the maximum hourglass sum

**Input Format**

Each of the *6* lines of inputs *arr[i]* contains *6* space-separated integers *arr[i][j]*.

**Constraints**
$$
-9 \leq arr[i][j] \leq 9 \\

0 \leq i,j \leq 5
$$

**Output Format**

Print the largest (maximum) hourglass sum found in *arr*.

**Sample Input**

$$
\begin{equation}
\begin{matrix}

1 & 1 & 1 & 0 & 0 & 0\\
0 & 1 & 0 & 0 & 0 & 0\\
1 & 1 & 1 & 0 & 0 & 0\\
0 & 0 & 2 & 4 & 4 & 0\\
0 & 0 & 0 & 2 & 0 & 0\\
0 & 0 & 1 & 2 & 4 & 0\\

\end{matrix}
\end{equation}
$$

**Sample Output**
```
19
```

**Explanation**

*arr* contains the following hourglasses:
$$
\begin{equation}
\begin{matrix}

1 & 1 & 1 && 1 & 1 & 0 && 1 & 0 & 0 && 0 & 0 & 0\\
  & 1 &   &&   & 0 &   &&   & 0 &   &&   & 0 &  \\
1 & 1 & 1 && 1 & 1 & 0 && 1 & 0 & 0 && 0 & 0 & 0\\[6pt]
0 & 1 & 0 && 1 & 0 & 0 && 0 & 0 & 0 && 0 & 0 & 0\\
  & 1 &   &&   & 1 &   &&   & 0 &   &&   & 0 &  \\
0 & 0 & 2 && 1 & 2 & 4 && 2 & 4 & 4 && 4 & 4 & 0\\[6pt]
1 & 1 & 1 && 1 & 1 & 0 && 1 & 0 & 0 && 0 & 0 & 0\\
  & 0 &   &&   & 2 &   &&   & 4 &   &&   & 4 &  \\
0 & 0 & 2 && 0 & 0 & 2 && 2 & 4 & 4 && 2 & 0 & 0\\[6pt]
0 & 0 & 2 && 0 & 2 & 4 && 2 & 4 & 4 && 4 & 4 & 0\\
  & 0 &   &&   & 0 &   &&   & 2 &   &&   & 0 &  \\
0 & 0 & 1 && 0 & 1 & 2 && 1 & 2 & 4 && 2 & 4 & 0\\

\end{matrix}
\end{equation}
$$

The hourglass with the maximum sum *(19)* is:

 $$
\begin{equation}
\begin{matrix}

2 & 4 & 4\\
  & 2 &  \\
1 & 2 & 4\\

\end{matrix}
\end{equation}
$$

In [41]:
# Given the matrix of the example, we calculate:

# Array given:
arr = [[1,1,1,0,0,0], [0,1,0,0,0,0], [1,1,1,0,0,0], [0,0,2,4,4,0], [0,0,0,2,0,0], [0,0,1,2,4,0]]

# Function obtain the maximum of the sum of the hourglasses:
def hourglassSum(arr):
    hg_vals = []
    for i in range(4):
        for j in range(4):
            top = arr[i][j] + arr[i][j+1] + arr[i][j+2]
            middle = arr[i+1][j+1]
            bottom = arr[i+2][j] + arr[i+2][j+1] + arr[i+2][j+2]
            hg_vals.append(top+middle+bottom)
    return max(hg_vals)
print(hourglassSum(arr))   

19


In [62]:
import numpy as np

# We define the function obtain the maximum of the sum of the hourglasses:
def maxHourglassSum(array):
    hourglass = []
    for i in range(4):
        for j in range(4):
            top = array[i][j] + array[i][j+1] + array[i][j+2]
            middle = array[i+1][j+1]
            bottom = array[i+2][j] + array[i+2][j+1] + array[i+2][j+2]
            hourglass.append(top + middle + bottom)
    return max(hourglass)

# We generate a square matrix with the restrictions of the exercise:
row = int(input('Enter the numer of rows: '))
col = int(input('Enter the numer of columns: '))

# We define the conditions for the restrictions:
if row == col & (row or col) <= 6:                                        # Square matrix + Less than or equal to 6 dimensions
    array = np.random.randint(low=-9, high=9, size=(row, col))            # Conditions
    print('The generated 2D array is: \n', array)
    print('The hourglass with the maximum sum: \n', maxHourglassSum(array))
else:
    print('The row and column numbers must be the same and, less than or equal to 6, a square matrix is expected.')

The generated 2D array is: 
 [[-2 -7 -3 -6 -9 -7]
 [-6  8  6 -1 -2  8]
 [-5  2 -3 -8 -4  4]
 [ 6  8  4 -7  0 -8]
 [ 4  1 -5  3  8 -8]
 [ 8 -6 -7  8 -7  4]]
The hourglass with the maximum sum: 
 28
